### ISSUE TITLE
support SCSS ？

### ISSUE THREAD

**Issue by cq112233** [wangzongming/vite-plugin-css-modules#1]

**Comment by wangzongming** [comment]
regExp: /.(scss)$/,

**Comment by cq112233** [comment]
An error was reported in the VUE SCF. Procedure
`
<style lang="scss" scoped >
.css {
  color: blue;
}
</style>
`
`[vite] Internal server error: ENOENT: no such file or directory, open '/Users/zhangshuifan/Desktop/vue-cqen-admin-better/src/views/lang/index.vue?vue&type=style&index=0&scoped=f4936bf7&lang.scss'`

**Comment by wangzongming** [comment]
用下面配置试试

```
{
  precompilers : [
          {
              regExp: /.(scss)$/,
              ompiler: async (code, file) => {
                  // 下面是 less 案例， 自行调用 scss 进行编译
                  const cssCode = (
                      await nodeLess.render(code, {
                          syncImport: true,
                          javascriptEnabled: true,
                      })
                  ).css;
                  return cssCode
              }
          }
    ]
}
```

**Comment by cq112233** [comment]
import vitePluginCssModules from 'vite-plugin-css-modules'
import nodeSass from 'sass'
const pluginCssModules = () => {
  return vitePluginCssModules.default({
    precompilers: [
      {
        regExp: /.(scss)$/,
        ompiler: async (code, file) => {
          // 下面是 less 案例， 自行调用 scss 进行编译
          const cssCode = (
            await nodeSass.render(code, {
              syncImport: true,
              javascriptEnabled: true,
            })
          ).css;
          return cssCode
        }
      }
    ]
  })
}
export default pluginCssModules

还是报错-。-！
